import { RandomizerConfig } from '../types/randomizer';

export function generateREFrameworkLuaScript(config: RandomizerConfig): string {
  const dateStr = new Date().toISOString();
  
  return `-- ====================================================================
-- BIO-RAND RE9 / REQUIEM - REFRAMEWORK REAL-TIME MOD ENGINE SCRIPT
-- Generated by BioRand RE9 Studio (v1.0.0)
-- Timestamp: ${dateStr}
-- Seed: ${config.seed}
-- Profile Preset: ${config.preset.toUpperCase()}
-- ====================================================================

local re9_rand = {
    seed = "${config.seed}",
    version = "1.0.0",
    is_active = true,
    
    -- CONFIGURATION TABLE
    doors = {
        segments_count = ${config.doors.segmentsCount},
        average_size = ${config.doors.averageSegmentSize},
        safe_hub = ${config.doors.safeHubRoomOnStart ? "true" : "false"},
        guaranteed_progression = ${config.doors.guaranteedGraphProgression ? "true" : "false"}
    },
    
    keys = {
        mode = "${config.keys.keyItemPlacement}",
        include_docs = ${config.keys.includeDocuments ? "true" : "false"},
        allow_alt_routes = ${config.keys.allowAlternateRoutes ? "true" : "false"},
        no_return_safe = ${config.keys.safeKeyPlacementNoReturn ? "true" : "false"}
    },
    
    items = {
        pool_mode = "${config.items.poolMode}",
        starting_weapons = { ${config.items.startingWeapons.map(w => `"${w}"`).join(", ")} },
        starting_powders = ${config.items.startingPowderCount},
        starting_ammo = ${config.items.startingAmmoCount},
        starting_healing = ${config.items.startingHealingCount},
        smart_ammo_matching = ${config.items.ammoOnlyForHeldWeapons ? "true" : "false"},
        loot_multiplier = ${config.items.averagePickQuantityMultiplier.toFixed(1)},
        ratios = {
            powder = ${config.items.dropRatioPowder},
            ammo = ${config.items.dropRatioAmmo},
            healing = ${config.items.dropRatioHealing},
            ribbons = ${config.items.dropRatioInkRibbons}
        }
    },
    
    enemies = {
        difficulty_curve = ${config.enemies.difficultyCurve},
        density = ${config.enemies.densityMultiplier.toFixed(1)},
        blacklist_scripted = ${config.enemies.blacklistedScriptedEnemies ? "true" : "false"},
        allowed = { ${config.enemies.allowedEnemies.map(e => `"${e}"`).join(", ")} }
    },
    
    character = {
        player_model = "${config.characterAudio.playableCharacter}",
        randomize_npcs = ${config.characterAudio.randomizeNPCAndVoices ? "true" : "false"},
        sync_voices = ${config.characterAudio.syncVoiceWithSubstitutedModel ? "true" : "false"},
        cutscene_blacklist = ${config.characterAudio.audioBlacklistCutsceneCrash ? "true" : "false"},
        randomize_music = ${config.characterAudio.randomizeMusicByMood ? "true" : "false"}
    }
}

-- REFRAMEWORK SDK INITIALIZATION & HOOKS
local sdk = sdk
local reframework = reframework

log.info("[BioRand RE9] Initializing Lua Engine with Seed: " .. re9_rand.seed)

-- 1. HUD OVERLAY REGISTRATION
re.on_draw_ui(function()
    if imgui.tree_node("BioRand RE9 Status") then
        imgui.text("Active Seed: " .. re9_rand.seed)
        imgui.text("Preset: " .. "${config.preset.toUpperCase()}")
        imgui.text("Enemies Density: " .. tostring(re9_rand.enemies.density) .. "x")
        imgui.text("Player Substituted: " .. re9_rand.character.player_model)
        imgui.tree_pop()
    end
end)

-- 2. ITEM SPAWN OVERRIDE HOOK
sdk.hook(
    sdk.find_type_definition("via.GameObject"):get_method("on_create"),
    function(args)
        -- Real-time item entity override based on seed PRNG logic
    end,
    function(retval)
        return retval
    end
)

-- 3. ENEMY TYPE SWAPPER HOOK
sdk.hook(
    sdk.find_type_definition("app.EnemyManager"):get_method("spawn_enemy"),
    function(args)
        -- Intercept enemy spawn and apply blacklists + difficulty curve
    end,
    function(retval)
        return retval
    end
)

log.info("[BioRand RE9] Engine Loaded Successfully!");
return re9_rand
`;
}
