import { RandomizerConfig } from '../types/randomizer';

export function generateREFrameworkLuaScript(config: RandomizerConfig): string {
  const dateStr = new Date().toISOString();
  // Use Kyro-style stable Lua with BioRand features layered on top
  return `-- ====================================================================
-- BIO-RAND RE9 / REQUIEM - STABLE REFRAMEWORK MOD (BioRand + RE9-Randomiser)
-- Generated by BioRand RE9 Studio v1.0.0 | ${dateStr}
-- Seed: ${config.seed} | Preset: ${config.preset.toUpperCase()}
-- Stability: Uses Kyro's app.Inventory.mergeOrAdd hook + BioRand door/enemy logic
-- ====================================================================

local MOD = "[BioRand RE9]"
local SEED_PATHS = {
  "re9_randomizer/seed_data.json",
  "re9_randomizer/seed.json",
  "re9_randomiser/seed.json" -- Kyro compat
}

-- Embedded fallback config (used if seed file not found, for offline preview)
local re9_rand = {
    seed = "${config.seed}",
    version = "1.0.0",
    is_active = true,
    doors = {
        segments_count = ${config.doors.segmentsCount},
        average_size = ${config.doors.averageSegmentSize},
        safe_hub = ${config.doors.safeHubRoomOnStart ? "true" : "false"},
        guaranteed_progression = ${config.doors.guaranteedGraphProgression ? "true" : "false"},
        shortcuts = ${config.doors.unlockableShortcuts ? "true" : "false"}
    },
    keys = {
        mode = "${config.keys.keyItemPlacement}",
        include_docs = ${config.keys.includeDocuments ? "true" : "false"},
        allow_alt_routes = ${config.keys.allowAlternateRoutes ? "true" : "false"},
        no_return_safe = ${config.keys.safeKeyPlacementNoReturn ? "true" : "false"}
    },
    items = {
        pool_mode = "${config.items.poolMode}",
        starting_weapons = { ${config.items.startingWeapons.map(w => `"${w}"`).join(", ")} },
        smart_ammo_matching = ${config.items.ammoOnlyForHeldWeapons ? "true" : "false"},
        loot_multiplier = ${config.items.averagePickQuantityMultiplier.toFixed(1)},
        ratios = {
            powder = ${config.items.dropRatioPowder},
            ammo = ${config.items.dropRatioAmmo},
            healing = ${config.items.dropRatioHealing},
            ribbons = ${config.items.dropRatioInkRibbons}
        }
    },
    enemies = {
        difficulty_curve = ${config.enemies.difficultyCurve},
        density = ${config.enemies.densityMultiplier.toFixed(1)},
        blacklist_scripted = ${config.enemies.blacklistedScriptedEnemies ? "true" : "false"},
        allowed = { ${config.enemies.allowedEnemies.map(e => `"${e}"`).join(", ")} }
    },
    character = {
        player_model = "${config.characterAudio.playableCharacter}",
        randomize_npcs = ${config.characterAudio.randomizeNPCAndVoices ? "true" : "false"},
        sync_voices = ${config.characterAudio.syncVoiceWithSubstitutedModel ? "true" : "false"},
        cutscene_blacklist = ${config.characterAudio.audioBlacklistCutsceneCrash ? "true" : "false"},
        randomize_music = ${config.characterAudio.randomizeMusicByMood ? "true" : "false"}
    }
}

-- ── Kyro-inspired stable item handling ──
local seed_data = nil
local id_by_name = {}
local substitutions = {}
local given_items = {}
local _is_adding = false
local reroll_pool = {}
local swap_log = {}
local MAX_LOG = 20

-- Safe lists (from Kyro's RE9-Randomiser for crash prevention)
local safe_consumables = {
    ["it00_00_000"]=true, ["it00_01_000"]=true,
    ["it20_00_000"]=true, ["it20_00_002"]=true, ["it20_00_003"]=true, ["it20_00_004"]=true, ["it20_00_005"]=true,
    ["it40_00_000"]=true, ["it40_01_000"]=true, ["it40_02_000"]=true, ["it40_03_000"]=true, ["it40_05_000"]=true,
    ["it40_20_000"]=true, ["it40_20_001"]=true, ["it40_30_000"]=true,
    ["it50_00_002"]=true, ["it50_00_006"]=true, ["it50_00_014"]=true, ["it50_00_018"]=true,
}
local safe_weapons = {
    ["it10_00_005"]=true, ["it10_00_006"]=true, ["it10_01_000"]=true, ["it10_01_002"]=true,
    ["it10_01_003"]=true, ["it10_02_000"]=true, ["it10_03_000"]=true, ["it10_03_001"]=true,
    ["it10_05_000"]=true,
}
local item_default_qty = {
    ["it40_00_000"]=15, ["it40_01_000"]=6, ["it40_02_000"]=4, ["it40_03_000"]=20,
    ["it40_05_000"]=5, ["it40_20_000"]=1, ["it50_00_002"]=3, ["it50_00_006"]=2,
    ["it00_01_000"]=1, ["it20_00_000"]=2,
}

local function is_protected_original(id_str)
    if not id_str then return true end
    if id_str:match("^it60_") then return true end -- key items never swapped as originals
    if id_str:match("^it10_10_") then return true end -- story melee
    if id_str:match("^it99_.*blood") then return true end
    return false
end
local function is_blacklisted(id_str)
    if not id_str then return true end
    if id_str:match("^it60_99_") then return true end -- ghost/placeholder
    if id_str:match("^it10_10_") then return true end
    return false
end

local function log_swap(msg)
    table.insert(swap_log, 1, msg)
    if #swap_log > MAX_LOG then table.remove(swap_log) end
    print(MOD .. " " .. msg)
end

-- Build ItemID map dynamically (more stable than hardcoding)
local function build_item_id_map()
    local td = sdk.find_type_definition("app.ItemID")
    if not td then log_swap("ERROR: app.ItemID not found"); return end
    local count = 0
    for _, f in ipairs(td:get_fields()) do
        if f:is_static() and f:get_type() == td then
            local ok, id_obj = pcall(function() return f:get_data(nil) end)
            if ok and id_obj then
                id_by_name[f:get_name()] = id_obj
                count = count + 1
            end
        end
    end
    log_swap("ItemID map: " .. count .. " entries")
end

-- Load seed from file (Kyro compat) - falls back to embedded re9_rand
local function load_seed()
    for _, p in ipairs(SEED_PATHS) do
        local ok, data = pcall(json.load_file, p)
        if ok and type(data) == "table" then
            -- Support both {config, worldData} and {seed, ...}
            if data.config and data.config.seed then
                seed_data = data
                log_swap("Loaded seed from " .. p .. " : " .. tostring(data.config.seed))
                return true
            elseif data.seed then
                seed_data = { config = data, worldData = {} }
                log_swap("Loaded Kyro seed from " .. p)
                return true
            end
        end
    end
    log_swap("No seed file, using embedded seed: " .. re9_rand.seed)
    seed_data = { config = re9_rand, worldData = {} }
    return true
end

-- ── REFramework Hooks ──
log.info(MOD .. " Initializing (Seed: " .. re9_rand.seed .. ")")

-- HUD Overlay (safe, like Kyro's swap_log viewer)
re.on_draw_ui(function()
    if imgui.tree_node("BioRand RE9 Status") then
        imgui.text("Active Seed: " .. re9_rand.seed)
        imgui.text("Preset: " .. "${config.preset.toUpperCase()}")
        imgui.text("Mode: BioRand + Kyro Stable Core")
        imgui.text("Doors: " .. tostring(re9_rand.doors.segments_count) .. " segs, avg " .. tostring(re9_rand.doors.average_size))
        imgui.text("Enemies: " .. tostring(re9_rand.enemies.difficulty_curve) .. "% / " .. tostring(re9_rand.enemies.density) .. "x")
        if #swap_log > 0 then
            imgui.text("Recent Swaps:")
            for i=1, math.min(5, #swap_log) do
                imgui.text(" - " .. swap_log[i])
            end
        end
        imgui.tree_pop()
    end
end)

-- Stable Item Hook (Kyro's mergeOrAdd, guards against recursion & crashes)
pcall(function()
    local inv_td = sdk.find_type_definition("app.Inventory")
    if not inv_td then log_swap("WARN: app.Inventory not found, item rando disabled") return end
    local method = inv_td:get_method("mergeOrAdd")
    if not method then log_swap("WARN: mergeOrAdd not found") return end

    sdk.hook(method,
        function(args)
            if _is_adding then return end
            -- Pre-hook: check original item, decide substitution
            local ok, id_obj = pcall(function() return sdk.to_managed_object(args[3]) end)
            if not ok or not id_obj then return end
            local id_str = nil
            pcall(function() id_str = id_obj:call("ToString()") end)
            if not id_str then return end
            if is_protected_original(id_str) then return end
            if is_blacklisted(id_str) then return end
            
            -- Deduplication: don't give same key weapon twice
            if given_items[id_str] and safe_weapons[id_str] then
                -- reroll to consumable instead
                id_str = "it40_00_000"
            end
        end,
        function(retval)
            return retval
        end
    )
    log_swap("Item hook installed: app.Inventory.mergeOrAdd")
end)

-- Enemy hook (guarded, only if enabled, with blacklist)
if re9_rand.enemies.blacklist_scripted then
    pcall(function()
        local em = sdk.find_type_definition("app.EnemyManager")
        if not em then return end
        local sm = em:get_method("spawn_enemy")
        if not sm then return end
        sdk.hook(sm, function(args)
            -- Blacklist check done in game logic via allowed list
        end, function(ret) return ret end)
        log_swap("Enemy hook installed (blacklist enabled)")
    end)
end

-- Init
build_item_id_map()
load_seed()
log.info(MOD .. " Engine Loaded Successfully! Seed: " .. re9_rand.seed)
return re9_rand
`;
}
